### ISSUE TITLE
got 400 error when adding new account

### ISSUE THREAD

**Issue by StephySARS** [ReVanced/GmsCore#142]
system: Android 13 (H96MAX TV box with RK3528 soc)
microg version：v0.3.1.4.240913
got 400 error when adding new account. How to solve it please?
![image](https://github.com/user-attachments/assets/e10c5149-4296-4229-b1d1-ef7df25eb6ce)

**Comment by Hendrick91** [comment]
Oke

**Comment by Hendrick91** [comment]
Hendrick91

**Comment by oSumAtrIX** [comment]
Try upstream GmsCore

**Comment by shohan254682** [comment]
Rafsan All Tem Members Valo aco Sobai Amir kaj ta korra dau Fat kora akta message dau

**Comment by oSumAtrIX** [comment]
Reopen once you tried upstream.
