### ISSUE TITLE
MicroG app saying a message was sent but none appear.

### ISSUE THREAD

**Issue by NGSpace** [ReVanced/GmsCore#148]
On the app the number keeps increase but I am not seeing any notifications.

**Comment by oSumAtrIX** [comment]
Gonna need more information than that.

**Comment by NGSpace** [comment]
Latest version, what info should I send and how do I get it?

**Comment by NGSpace** [comment]
According to Revanced Manager.

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.
