### ISSUE TITLE
Can't Access Google Account Using Huawei

### ISSUE THREAD

**Issue by Solus32** [ReVanced/GmsCore#15]
Hello, i can't sign in using my google account using the last version of the ReVanced GmsCore v0.3.1.3.240913 on my Huawei without google services.

I was using the last version of Vanced v0.2.24220220 before updating Youtube  to the last version. Vanced had an option for Huawei without google services was working fine.

Now i can't use my Google Account with Youtube, can you fix it 

Thanks

**Comment by khalidsbaih** [comment]
i'm having the same issue here, it was working fine with the older microG, not with the GmsCore it's not signing in to google.

**Comment by rawen90** [comment]
This problem is already resolve https://github.com/ReVanced/GmsCore/issues/6#issuecomment-2020340735

**Comment by khalidsbaih** [comment]
@rawen90 , Many thanks this saved alot of my time searching for solution. this work like charm

**Comment by Solus32** [comment]
As a suggestion, you could put an option when starting the application to start in Huawei just like Vanced did, but the method mentioned above works.

Thank you
