### ISSUE TITLE
MicroG has crashed on Google Pixel 7 pro 

### ISSUE THREAD

**Issue by e36910** [ReVanced/GmsCore#150]
After logging into YouTube Revanced, the account is not added. It passes all verifications, but does not appear in the list of accounts, microG gives an error and closes. I try to open microG separately, it also gives an error and does not open. What should I do?

**Comment by oSumAtrIX** [comment]
Send crashlogs using logcat. Google how to.

**Comment by e36910** [comment]
[log.txt](https://github.com/user-attachments/files/16736059/log.txt)
my log via terminal with command - adb logcat

**Comment by oSumAtrIX** [comment]
Issue with your OS/Will happen with upstream GmsCore as well

**Comment by e36910** [comment]
[log.txt](https://github.com/user-attachments/files/16736067/log.txt)
log №2 with start and crash app

**Comment by e36910** [comment]
> Issue with your OS/Will happen with upstream GmsCore as well

How to fix GmsCore?
