### ISSUE TITLE
Excessive battery drain when enabling "battery optimizations igonored"

### ISSUE THREAD

**Issue by kruttgutten** [ReVanced/GmsCore#158]
When i opened yiutube after installing revanced the app told me to enable this setting as it could cause issues if not enabled, this however lead to my battery draining from full to about 30% in an hour of normal use. I was also not able to untick this setting and so the only way to fix it was to reinstall microG. I haven't had any bugs or issues after reinstalling and the battery drain seems normal too, so I don't understand why I would need it toggled. I also keep getting a promt to enable it every time i open youtube now which is pretty annoying.

My phone is a galaxy s23 ultra, running android 14

**Comment by oSumAtrIX** [comment]
Send a picture that shows GmsCore draining the battery in the battery usage settings

**Comment by kruttgutten** [comment]
![Image](https://github.com/user-attachments/assets/fbb9d70e-0870-4158-bff6-bf1bbcc9d195)
![Image](https://github.com/user-attachments/assets/b71ea923-1f50-4ad9-8915-182e1bda708e)
![Image](https://github.com/user-attachments/assets/f9f1bf33-68d8-424f-a335-bcd0310727ef)
![Image](https://github.com/user-attachments/assets/1ed498d5-d3c2-41d6-84e9-0f0ca987d95a)
Here are screenshots of the battery usage of youtube after installing revanced, and on the one for the 2nd of october you can see the rapid drain i mentioned, which is when i reinstalled microG. The 3 hrs 50 min screentime screenshot is from the 2nd of october. The 8 hrs 32 min one is from the day after when i had reinstalled microG. Claiming this has nothing to do with microG is absurd as my phone was noticably warm from light usage, which it hasn't been since i reinstalled microG. This is really making me question if this is some kinda bitcoinminer bullshit

**Comment by kruttgutten** [comment]
And again let me state that I am not able to change any settings in microG myself, I can't tick or untick any of the boxes. The only way i was even able to turn on the ignore thing was cus of the prompt in youtube

**Comment by oSumAtrIX** [comment]
Sure

**Comment by masterflitzer** [comment]
> All of it is just viewing 1080p videos. The main concern for me, which is hard to really show, was that my phone was heating up as if it was charging when using the youtube app. And it stayed really warm when I hadn't been using it for a good while too. This has not happened since i reinstalled. I can test it again to verify

i have the exact same since yesterday, just today i lost 62% battery through yt alone and my phone is very hot, while normally it's around 12-16% from yt, but i actually didn't patch yt recently (last time 1-2 weeks ago), and microg doesn't even appear in my battery drain graph, it's only yt, so I don't think it's revanced's fault at all, but for now i don't have any solution
