### ISSUE TITLE
[BUG] Shows "check internet connection" until cache is cleared

### ISSUE THREAD

**Issue by oleglucic** [ReVanced/GmsCore#164]
When using YouTube ReVanced with microG every few days it says no internet connection. Same happens when you login or add account. The only things that gets everything to work again is to clear microG app data from settings.  I hope you will look into this. : )

Android 14 (OneUI 6.1)
YouTube ReVanced 19.84.42
MicroG 0.3.1.4.240913

**Comment by oSumAtrIX** [comment]
Issue occurs upstream as well

**Comment by oleglucic** [comment]
Will it be resolved in the future?
