### ISSUE TITLE
Reduce apk size

### ISSUE THREAD

**Issue by webzeroacs** [ReVanced/GmsCore#17]
In my opinion, most Android devices at the moment are "armeabi-v7a," "arm64-v8a."
Reducing abiFilters "armeabi-v7a", "arm64-v8a", "x86", and "x86_64" to
"armeabi-v7a" and "arm64-v8a" is thought to reduce the total capacity.

Before: 37.8MB
After:    24.6MB

play-services-core\build.gradle
abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64" 
play-services-maps\core\hms\build.gradle
abiFilters "armeabi", "armeabi-v7a", "arm64-v8a" 
play-services-maps\core\mapbox\build.gradle
abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
play-services-maps\core\vtm\build.gradle
abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"

**Comment by oSumAtrIX** [comment]
There's no purpose in removing architectures. The fork would stop working on them
