### ISSUE TITLE
Sorry... there was a problem communicating with Google servers. Try again later

### ISSUE THREAD

**Issue by disconnect5852** [ReVanced/GmsCore#172]
Tried to log in several with this (BTW what is the difference from this? https://github.com/microg/GmsCore/releases ) but always after giving user, pass, complete the 2 step verification, at the end i get this ![Image](https://github.com/user-attachments/assets/2023fff0-c84b-4564-acf8-60fbfc20176d)
While if i try the original microG, i can log in just fine, but with that, the revanced patched apps telling me to install this kind of microG... This happening in a Waydroid virtual x86 android, on my real phone it works.
How to fix?

**Comment by oSumAtrIX** [comment]
Please send a recording of how upstream works but the fork doesn't

**Comment by oSumAtrIX** [comment]
To rule out user errors. Reopen once you attach the recording. You can censor private fields. Include how you download both apps as well in the recording.

**Comment by TheBill2001** [comment]
I can confirm that using [Waydroid](https://waydro.id/) on Arch Linux does not work and display the above error. However, I don't think this is an x86 vs ARM problem because ReVanced GmsCore work perfectly fine in a virtual machine with [Android x86](https://www.android-x86.org). Do note that neither Waydroid nor Android x86 running in a VM are emulator.

**Comment by Rahulbheda** [comment]
facing same issue anyone find any workaround

**Comment by GTRONICK** [comment]
For those wondering what the heck is "google device registration", in Waydroid follow this procedure:

1. Open microG Services app
2. Select Google device registration
3. Turn off Register Device
4. Go back
5. Select Google Accounts
6. Turn off Authenticate with device registration
7. Select Google account
8. Add google account

This worked for me.

**Comment by samikhan69420** [comment]
> For those wondering what the heck is "google device registration", in Waydroid follow this procedure:
> 
>     1. Open microG Services app
> 
>     2. Select `Google device registration`
> 
>     3. Turn off `Register Device`
> 
>     4. Go back
> 
>     5. Select `Google Accounts`
> 
>     6. Turn off `Authenticate with device registration`
> 
>     7. Select `Google account`
> 
>     8. Add google account
> 
> 
> This worked for me.

Any other solution? this isnt working for me, i am using it on Xiaomi Redmi Note 11

**Comment by samikhan69420** [comment]
I fixed it by installing the Huwawei version.
