### ISSUE TITLE
Spoofing not working?

### ISSUE THREAD

**Issue by GuiSaiUwU** [ReVanced/GmsCore#22]
![Screenshot_20240328_171053_microG Services.jpg](https://github.com/ReVanced/GmsCore/assets/107002177/0bd08446-3800-4efb-be69-cc8ef20bb7e9)

Idk why is it auto translated, but the self check tab shows up that spoofing isnt working and signature also isnt. In revanced youtube I get buffering issues, the video loads around 30 seconds and stops.

**Comment by oSumAtrIX** [comment]
That's not an issue, for support move to our links at https://revanced.app

**Comment by GuiSaiUwU** [comment]
> That's not an issue, for support move to our links at https://revanced.app

I asked in discord nobody reply, in the announcement about GmsCore says to open an issue in github

**Comment by oSumAtrIX** [comment]
Like I said this is not an issue so move to one of the links
