### ISSUE TITLE
Can't install GMSCore due to Play Protect?

### ISSUE THREAD

**Issue by chuawilly** [ReVanced/GmsCore#29]
Haven't seen anyone mentioning this issue on Github / Reddit. When I try to install GMS Core, and error would show "App blocked to protect your device". 

There is no option to let me install anyway or ignore the warning. The installation will just show up as unsuccessful

![photo_2024-04-01_20-00-21](https://github.com/ReVanced/GmsCore/assets/138508822/d7721b7e-a71d-4f5f-aec5-adffc60a5db4)

**Comment by oSumAtrIX** [comment]
That's something you'll need to resolve on your end. Probably your device admin blocked that

**Comment by chuawilly** [comment]
Thanks oSum. There's no device admin though; it is a personal device, and I did not have this issue with MicroG previously

**Comment by oSumAtrIX** [comment]
That's not in our control. Your device is setup to allow Google to block apps at free will. Contact their support.
