### ISSUE TITLE
this repo should track microg/GmsCore

### ISSUE THREAD

**Issue by alexsch01** [ReVanced/GmsCore#3]
Currently https://github.com/ReVanced/GmsCore tracks https://github.com/oSumAtrIX/GmsCore which is an archived repo

---

https://github.com/ReVanced/GmsCore should track https://github.com/microg/GmsCore

**Comment by oSumAtrIX** [comment]
It tracks microg/GmsCore already. What GitHub displays can't be changed.

**Comment by alexsch01** [comment]
gotcha

**Comment by Indranil012** [comment]
It doesn't have many stars so, depleting it now should be a good idea.

**Comment by oSumAtrIX** [comment]
Deleting oSumAtrIX/GmsCore worked.

**Comment by Indranil012** [comment]
Oh nice!
