### ISSUE TITLE
Can't install gmscore

### ISSUE THREAD

**Issue by styx-uwu** [ReVanced/GmsCore#31]
![IMG-20240401-WA0001](https://github.com/ReVanced/GmsCore/assets/69765467/93bece8e-69e9-478c-84cf-1fe424906249)

For additional information
This is my friend's device, running android 11

**Comment by oSumAtrIX** [comment]
Use SAI or ADB to install it and retrieve the error message

**Comment by styx-uwu** [comment]
What is SAI?

**Comment by oSumAtrIX** [comment]
SAI is an app installer. Please research the terms yourself and send the the installer error message.

**Comment by styx-uwu** [comment]
Ok, thanks

**Comment by styx-uwu** [comment]
No, my friend's phone never installed micro g before. Now it can be installed using SAI

**Comment by Mata-L** [comment]
![Image](https://github.com/user-attachments/assets/f75f6847-9452-4f68-8ecd-b1c3badafd96)
![Image](https://github.com/user-attachments/assets/6dffeb21-d27b-480e-86be-e1be1227e0a2)

my problem is solved. ty! 🦝
