### ISSUE TITLE
GmsCore Issues: ReVanced crashed while watching videos randomly

### ISSUE THREAD

**Issue by WildCatApp** [ReVanced/GmsCore#32]
After updating ReVanced for the playback issues recently, a new issue arose for some people including me. It's not a battery optimization issue. I have battery optimization disabled for YouTube.

Some logs:

Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
 [RequestTokenManager] getToken() -> BAD_AUTHENTICATION. App: com.google.android.gms, Service: oauth2:********************************
 
 
 E AuthPII : aghg: Long live credential not available.
 E AuthPII :      at rgd.a(:com.google.android.gms@233717037@23.37.17 ():993)
 E AuthPII :      at rgk.b(:com.google.android.gms@233717037@23.37.17 ():26)
 E AuthPII :      at rgh.a(:com.google.android.gms@233717037@23.37.17 ():612)
 E AuthPII :      at qsc.a(:com.google.android.gms@233717037@23.37.17 ():82)
 E AuthPII :      at lpv.f(:com.google.android.gms@233717037@23.37.17 ():97)
 E AuthPII :      at lpv.c(:com.google.android.gms@233717037@23.37.17 ():1032)
 E AuthPII :      at lpv.h(:com.google.android.gms@233717037@23.37.17 ():2)
 E AuthPII :      at lpv.eY(:com.google.android.gms@233717037@23.37.17 ():147)
 E AuthPII :      at lnw.onTransact(:com.google.android.gms@233717037@23.37.17 ():117)
 E AuthPII :      at android.os.Binder.transact(Binder.java:1043)
 E AuthPII :      at bamr.onTransact(:com.google.android.gms@233717037@23.37.17 ():10)
 E AuthPII :      at android.os.Binder.transact(Binder.java:1043)
 E AuthPII :      at atsb.onTransact(:com.google.android.gms@233717037@23.37.17 ():147)
 E AuthPII :      at android.os.Binder.execTransactInternal(Binder.java:1154)
 E AuthPII :      at android.os.Binder.execTransact(Binder.java:1123)
 E AuthPII : Message is Long live credential not available.
 E AuthPII : aghg: Long live credential not available.
 E AuthPII :      at rgd.a(:com.google.android.gms@233717037@23.37.17 ():993)
 E AuthPII :      at rgk.b(:com.google.android.gms@233717037@23.37.17 ():26)
 E AuthPII :      at rgh.a(:com.google.android.gms@233717037@23.37.17 ():612)
 E AuthPII :      at qsc.a(:com.google.android.gms@233717037@23.37.17 ():82)
 E AuthPII :      at lpv.f(:com.google.android.gms@233717037@23.37.17 ():97)
 E AuthPII :      at lpv.c(:com.google.android.gms@233717037@23.37.17 ():1032)
 E AuthPII :      at lpv.h(:com.google.android.gms@233717037@23.37.17 ():2)
 E AuthPII :      at lpv.eY(:com.google.android.gms@233717037@23.37.17 ():147)
 E AuthPII :      at lnw.onTransact(:com.google.android.gms@233717037@23.37.17 ():117)
 E AuthPII :      at android.os.Binder.transact(Binder.java:1043)
 E AuthPII :      at bamr.onTransact(:com.google.android.gms@233717037@23.37.17 ():10)
 E AuthPII :      at android.os.Binder.transact(Binder.java:1043)
 E AuthPII :      at atsb.onTransact(:com.google.android.gms@233717037@23.37.17 ():147)
 E AuthPII :      at android.os.Binder.execTransactInternal(Binder.java:1154)
 E AuthPII :      at android.os.Binder.execTransact(Binder.java:1123)
 I Auth    : (REDACTED) [AccountIdManager] Token response failed with status=%s
E AuthPII : [RequestTokenManager] getToken() -> BAD_AUTHENTICATION. App: com.google.android.gms, Service: oauth2:*************************** ***************************** ****************************
 E AuthPII : aghg: Long live credential not available.

**Comment by oSumAtrIX** [comment]
The package name does not match this repos released package.

**Comment by WildCatApp** [comment]
@oSumAtrIX

**Comment by oSumAtrIX** [comment]
Looks like an issue with GmsCore upstream. Please report the issue in a proper manner to upstream.
