### ISSUE TITLE
Trouble Adding Google Account on MicroG Gmscore (Xiaomi)

### ISSUE THREAD

**Issue by AwkBoyy** [ReVanced/GmsCore#37]
**Problem Description**
As I've updated to the latest MicroG Gmscore version (app.revanced.android.gms-241017000), I'm encountering an issue when trying to add my Google account. Previously, on the older MicroG version, I had no trouble signing in and add google account for YouTube Revanced. 

However, with the newest version, I'm consistently encountering the error message: "**There was a problem communicating with Google servers.**"

My device operates on a 'Pixel Experience' custom ROM. I'm unsure of the exact cause behind this. Any guidance on how to successfully add my account would be greatly appreciated.

**System**
Android Version: 13
Device: Xiaomi Redmi
Custom ROM: Pixel Experience

![IMG_20240403_000115](https://github.com/ReVanced/GmsCore/assets/162299150/0d778724-050f-4d10-95dc-606f5042a3a3)

**Comment by oSumAtrIX** [comment]
Try https://github.com/ReVanced/GmsCore/issues/6

**Comment by AwkBoyy** [comment]
The latest version provided for Huawei/Xiaomi has resolved the issue. Thank you.
