### ISSUE TITLE
Google Chromecast HD

### ISSUE THREAD

**Issue by TommyVirus** [ReVanced/GmsCore#4]
Hi, just got revanced manager running, patched the youtube app on my google chromecast hd and installed gmscore but now it says gmscore is not installed.
under self-check, "system spoof signature" and "play services (gmscore) has correct signature" is unchecked, is there anyway to get this running?
and big thanks for your great app

**Comment by Sam101011** [comment]
Signature spoofing is quite complicated(and straight upimpossible if you're on a Huawei like me). For more instructions, check this page:
https://github.com/microg/GmsCore/wiki/Signature-Spoofing.

**Comment by oSumAtrIX** [comment]
The error you experience has nothing to do with Chromecast or spoofing. If you are seeing that toast, you should also be automatically redirected to the correct download page for GmsCore. For support move to one of our links at https://revanced.app

**Comment by oSumAtrIX** [comment]
Like I said this is not the place for support
