### ISSUE TITLE
Cannot go to password dialog when sign-in

### ISSUE THREAD

**Issue by qtotter** [ReVanced/GmsCore#44]
Hi, 

I have no problem using this micro g on pixel 8 pro, but when I do the same on pixel tablet, I cannot move onto the password dialog after typing Google account email address and tapping next. It just loops back to the email dialog...

Any advice? Thanks.

**Comment by oSumAtrIX** [comment]
Use logcat (Check online articles on how) to capture logs when tapping next. Make sure you capture only relevant logs as they contain private information.
