### ISSUE TITLE
Continuous YT crash while watching Shorts

### ISSUE THREAD

**Issue by Vipin2003** [ReVanced/GmsCore#45]
In New microg, YT is keep crashing while watching shorts. During Shorts, it crashes after watching 7-8 shorts and attempt automatically restart. I've tried on 2 devices but same result. Also tried clean install microg+ YT.
Need a fix for that.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2966#issuecomment-2037158254
