### ISSUE TITLE
Double Chromecast name listed 

### ISSUE THREAD

**Issue by EnomiZ** [ReVanced/GmsCore#46]
![Screenshot_2024-04-04-19-48-41-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ReVanced/GmsCore/assets/75144327/122d1528-7dcf-4ca3-98f9-abffd9db433b)

**Comment by EnomiZ** [comment]
The issue is caused by microg

**Comment by oSumAtrIX** [comment]
Proof if

**Comment by EnomiZ** [comment]
It is cause by gmscore.. but don't worry I will just stop using it and revanced. Thank you anyway you are very very kind!

**Comment by EnomiZ** [comment]
Sei un ritardato

Il gio 4 apr 2024, 20:19 oSumAtrIX ***@***.***> ha scritto:

**Comment by oSumAtrIX** [comment]
Screenshot?

**Comment by CaptBillGates** [comment]
> Screenshot?

@DaddyNix Is correct. The previous version had an option to fix the duplicate cast names.

Steps:
Open YouTube (ReVanced) -> Click Name/Profile in top right corner -> Settings: https://ibb.co/mvxzG9W

After clicking on MicroG Settings: https://ibb.co/ysKfScf

I have an old phone running the previous version of ReVanced YouTube where the setting from the screenshots above was taken.
ReVanced Manager version: 1.17.1 (not sure what version of patches was used)
Patched Youtube version: 18.37.36
Vanced MicroG version: 0.2.24.220220

Hope that helps!
