### ISSUE TITLE
Signature spoofing not working

### ISSUE THREAD

**Issue by JimZiii** [ReVanced/GmsCore#5]
I got a samsung galaxy a52 and the new gmscore haven't fixed buffering with spoofing turned off.  
If i check self-check in gmscore two of them aren't activated.
"System spoofs signature"
"Play services (gmscore) has correct signature"

Any way i can activate those?
Ive been using the old vanced version of microg till now which didnt have all these other settings so just wanna make sure i havent missed something

**Comment by oSumAtrIX** [comment]
Consult the wiki in the README for spoofing. You will need to handle the change of the group id from original GmsCore manually. For support move to one of our links at https://revanced.app

**Comment by JeremyLaurent** [comment]
Could you please give a litte bit more details ? It seems like now if you have a non supported rom (like vanilla android on a pixel) then you can't do signature spoofing which means the issue where a video stops after 30 sec is back. Is there a way around this I'm not seeing?

**Comment by JeremyLaurent** [comment]
nevermind I didn't enable client spoofing, if you're seeing the issue with the video stopping at 30 sec make sure to enable client spoofing in settings -> revanced -> general layout

**Comment by JimZiii** [comment]
> nevermind I didn't enable client spoofing, if you're seeing the issue with the video stopping at 30 sec make sure to enable client spoofing in settings -> revanced -> general layout

If the gmscore from revanced isn't working, try the one from yt-advanced, that fixed it for me

https://github.com/YT-Advanced/GmsCore/releases
