### ISSUE TITLE
Considering not advertising to Xiaomi users to download the HW version

### ISSUE THREAD

**Issue by trmdi** [ReVanced/GmsCore#50]
Unlike Huawei phones, not all Xiaomi ones are uncertified from Google, they can login without having to apply specific Huawei setting. While applying that setting could have some unforeseen consequences like microG says:

![Screenshot_2024-04-05-11-51-41-316-edit_app revanced android gms](https://github.com/ReVanced/GmsCore/assets/11857205/87f95468-9c60-40c1-933a-8d6c75733c87)

So in the release page, we should only suggest Xiaomi phones(and maybe other ones running custom rom?) to try the -hw version only if login fails, but should not advertise Xiaomi users to always use that file.

![Screenshot_2024-04-05-11-57-29-052-edit_com sec android app sbrowser](https://github.com/ReVanced/GmsCore/assets/11857205/11d1a80c-5105-4b42-8c75-38ac60227acc)

**Comment by oSumAtrIX** [comment]
Until any issues arise with the HW release for Xiaomi users, we should not delegate the choice to users who don't know better. The change was done out of necessity to close https://github.com/ReVanced/GmsCore/issues/37.

If there's anything else, let me know.

**Comment by oSumAtrIX** [comment]
If this setting needs to be off for uncertified devices, is it necessary to toggle the setting off for any custom ROM?

**Comment by oSumAtrIX** [comment]
I am asking about custom roms in general, do they count as uncertified and would they need the Huawei version?

**Comment by oSumAtrIX** [comment]
I have tested on a Gappsless emulator and the hw version was not necessary.
