### ISSUE TITLE
it Show App Not Installed

### ISSUE THREAD

**Issue by ulil-azmy** [ReVanced/GmsCore#51]
I download it from this release, then try to install, but it show App Not Installed. no other variation of MicroG or GMS installed. 
my device: Redmi Note 8

**Comment by oSumAtrIX** [comment]
Use SAI or ADB to install it and capture the additional error message that appears.

**Comment by Astrosp** [comment]
@ulil-azmy uninstall previous version then install this "https://github.com/ReVanced/GmsCore/releases/download/v0.3.1.4.240913/app.revanced.android.gms-240913008-hw-signed.apk"
