### ISSUE TITLE
It's huge takes 200MB and No OPTION to hide app from launcher like previous 

### ISSUE THREAD

**Issue by abdarker** [ReVanced/GmsCore#52]
i was expecting something like this a very small size app with launcher icon hide

https://github.com/WSTxda/MicroG-RE/releases/tag/5.3

**Comment by abdarker** [comment]
> Not officially by revanced, report bug to respective owner/dev

i know it's not official. i just give example and expecting something small in size like that. just example.

**Comment by oSumAtrIX** [comment]
Neither is it 200Mb but 35Mb, nor is hiding the app icon contributing to the goal of this fork.

**Comment by abdarker** [comment]
> Neither is it 200Mb but 35Mb, nor is hiding the app icon contributing to the goal of this fork.

after installation it's 200mb+ and it is increasing. just letting you know.

**Comment by oSumAtrIX** [comment]
This is a matter of upstream. See the about fork section of the readme. In my case it's about 70MB

**Comment by MtndaleRedneck** [comment]
Didn't think about it so I just checked. 224mb by me. What's going on? Why is it growing??

**Comment by MtndaleRedneck** [comment]
I'm not worried. I have a ton of free space and don't care. I'm just curious about it, especially after the other commentator posted about it.
