### ISSUE TITLE
Cast duplication fix & Slimmed down Microg

### ISSUE THREAD

**Issue by Covkie** [ReVanced/GmsCore#56]
Vanced Microg had the cast entry duplication fix along with a slimmed down microg service to only facilitate Google account authentication. 

Implementing this would bring this ReVanced fork of GmsCore into parity of the now broken Vanced fork.

**Comment by oSumAtrIX** [comment]
Bug fixes that do not contribute to the goal of this fork should be opened upstream.

https://github.com/ReVanced/GmsCore#about-this-fork

**Comment by oSumAtrIX** [comment]
That opens the MicroG settings. Where is the "Cast duplication fix"?

**Comment by ILoveOpenSourceApplications** [comment]
It looks like there was such a toggle within the old Vanced microG settings.
![Screenshot_20240413_013409_Vanced microG](https://github.com/ReVanced/GmsCore/assets/117499019/42f3b82f-3ed3-437c-ae9e-a01ea0e7cac7)

**Comment by oSumAtrIX** [comment]
Apparently just disables Casting in GmsCore: https://github.com/TeamVanced/VancedMicroG/blob/6814161c486b297f4e723cd3365f1d0538c6f392/play-services-core/src/main/kotlin/org/microg/gms/ui/SettingsFragment.kt#L51.

This is a non-goal of GmsCore and an issue in patched apps instead. Please open an issue in the patches repository regarding this issue with GmsCore support patch.

**Comment by oSumAtrIX** [comment]
It is an issue of the patch handling it, not GmsCore. GmsCore provides the functionality correctly, but the application using it does not.

**Comment by david-kalbermatten** [comment]
For what's it worth. I agree with OP. Denying this obvious problem is likely _rooted_ in the lack urgency for someone who doesn't need microg and therefore doesn't have the issue affect them smh...

**Comment by oSumAtrIX** [comment]
Except I both, use GmsCore as well as reproduce the issue with the GmsCore support patch. I have already explained how the problem must be solved in my previous comment.
