### ISSUE TITLE
Can't sign in to school account.

### ISSUE THREAD

**Issue by rainlessness** [ReVanced/GmsCore#57]
When i enter my school mail to sign in, it says you'll be sent there to finish signing in, but when i continue, it just stucks there.

https://github.com/ReVanced/GmsCore/assets/96870840/1e4f5bbe-8289-4c93-a570-02418e0c7e01

**Comment by oSumAtrIX** [comment]
Report to upstream 

https://github.com/ReVanced/GmsCore?tab=readme-ov-file#about-this-fork
