### ISSUE TITLE
Logging into microg replaces the google accounts page in android settings

### ISSUE THREAD

**Issue by LOCKhart07** [ReVanced/GmsCore#60]
After logging in using microg, in android settings > Users & Accounts > Google, there's only the account that was signed in using microg. None of the accounts added normally through android for drive, gmail etc. show up. 
This is preventing the user from managing/removing those accounts. 

Devices tested: Oneplus Nord CE3, Oneplus 11R

**Comment by oSumAtrIX** [comment]
This is an issue with your OS. All accounts do show up next to the one for GmsCore.
