### ISSUE TITLE
“There was a problem communicating with Google servers”

### ISSUE THREAD

**Issue by JapanYoshi** [ReVanced/GmsCore#63]
![Screenshot_2024-04-15-22-32-55-65_4d4502106e9b52bcf4203a2f61fac539](https://github.com/ReVanced/GmsCore/assets/8707990/4cf42e48-967c-4cb8-9a35-e0f24c015fb7)
Accounts stopped working in YT ReVanced, and MicroG stopped being able to connect to Google

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/GmsCore/issues/37
