### ISSUE TITLE
Cannot install GmsCore.

### ISSUE THREAD

**Issue by yuukiAme** [ReVanced/GmsCore#7]
I downloaded the new release of GmsCore from [the release page](https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.1.240913)
that has the name `app.revanced.android.gms-240913002-signed.apk`

I uninstalled the old MicroG Services and tried to install the new version of GmsCore.

Error below
```
microG Services
App not installed as package conflicts with an existing package
```

But in my app list, there is no microG Services on the device. 

Screenshots below

![Screenshot_20240326_202021_Settings](https://github.com/ReVanced/GmsCore/assets/45681604/15c40b4c-a229-44f4-a6fb-59ba74d94b2d)

![Screenshot_20240326_202122_Settings](https://github.com/ReVanced/GmsCore/assets/45681604/974120ff-16b2-469f-a306-916a2270ee2b)

![Screenshot_20240326_202145_Settings](https://github.com/ReVanced/GmsCore/assets/45681604/b87733e6-1748-4305-bc52-4434a8de0202)

How do I fix this error? I thought the MicroG or GmsCore is fully uninstalled from the user package list.

EDIT: fixed a typo in error

**Comment by smarttommyau** [comment]
I think you can follow this post https://www.reddit.com/r/androidapps/comments/u9drlb/i_want_to_install_an_apk_but_it_shows_app_not/

**Comment by yuukiAme** [comment]
@oSumAtrIX @smarttommyau 

1. Get a PC and connect the phone with a USB
2. Enable developers option
3. Enable USB debugging
4. Download ADB shell
5. Open CMD and type: `adb devices`
6. Allow access on my device
7. Command: `pm list package -u`

`Shell does not have permission to access user 150` so it failed

8. Check for `app.revanced.android.gms`  using `pm list package --user 0 | grep "revanced"`

```
C:\platform-tools>adb shell
* daemon not running; starting now at tcp:5037
* daemon started successfully
gts8p:/ $ pm list package --user 0 | grep "revanced"
package:app.revanced.manager.flutter

```

So only **Revanced Manager** showed up.

9. Check for other names that other developers used for gmscore or microG and searching only for `gms`

```
1|gts8p:/ $ pm list packages --user 0 | grep "rvx"
1|gts8p:/ $ pm list packages --user 0 | grep "mgoogle"
1|gts8p:/ $ pm list packages --user 0 | grep "gms"
package:com.google.android.overlay.gmsconfig.asi
package:com.google.android.gms.location.history
package:com.google.android.overlay.gmsconfig.geotz
package:com.google.android.gms.supervision
package:com.google.android.gms
package:com.google.android.overlay.gmsconfig.searchselector
package:com.google.android.overlay.gmsconfig.photos
package:com.google.android.overlay.gmsconfig.gsa
package:com.google.android.overlay.gmsconfig.common
gts8p:/ $
```

10. Reinstall the package using this command: `adb shell cmd package install-existing package-name`

```
C:\platform-tools>adb shell
gts8p:/ $ pm install-existing app.revanced.android.gms
android.content.pm.PackageManager$NameNotFoundException: Package app.revanced.android.gms doesn't exist
1|gts8p:/ $
```

Of course the package isn't in the system.

What are my next steps?

**Comment by yuukiAme** [comment]
@oSumAtrIX 

> Please use adb or SAI to install the latest release of GmsCore, like I said before.

I renamed `app.revanced.android.gms` to `file.apk` and placed it in the same folder as adb. 
I tried to install it with `adb install file.apk`. It failed.

```
C:\platform-tools>adb install file.apk
Performing Streamed Install
adb: failed to install file.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package app.revanced.android.gms attempting to redeclare permission org.microg.gms.PROVISION already owned by app.rvx.android.gms]

C:\platform-tools>

```

So my install failed because its location is taken. How do I get rid of it? The problem is clearly 

```
Package app.revanced.android.gms attempting to redeclare permission org.microg.gms.PROVISION already owned by app.rvx.android.gms]
```

**Comment by yuukiAme** [comment]
@cyberboh 

> Uninstall RVX related apps in this case could be RVX MicroG

I can't find it. I already uninstalled RVX and Revanced Extended and its Manager. Couldn't find it with ADB Shell either.
