### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by shenmuejon** [ReVanced/GmsCore#71]
Seconds into YouTube video and it buffers forever.

**Comment by sumabob** [comment]
My HarmonyOS phone is also having this problem. It didn't have this problem four days ago
0.3.1.3.240913 This problem does not occur

**Comment by nedkoff** [comment]
I have tested versions 0.3.1.1, 0.3.1.3, and 0.3.1.4 of the software on a Redmi device running HarmonyOS and encountered random buffering issues.
