### ISSUE TITLE
change app icon and/or label (name in launcher) to differ from original microg

### ISSUE THREAD

**Issue by konradmoesch** [ReVanced/GmsCore#84]
I use the official microg (spoofing as com.google.android.gms), but for revanced, I had to install this package (app.revanced.android.gms)

I am okay with having to install microg two times, but now I have two "microg settings" apps in the launcher. If I want to open microg settings (only ever want to open the official settings, since revanced.android.gms is only used once for logging in), I have to guess which one.

Since I am no longer able to hide it, please at least change the icon (background color would be enough) or the app label. Having two apps that look the same is really annoying.

**Comment by Ushie** [comment]
You can mount YouTube ReVanced with root ontop of the original YouTube app and you won't need to install ReVanced GmsCore

**Comment by oSumAtrIX** [comment]
#59

**Comment by konradmoesch** [comment]
I don't use root, so I need revanced-microg. Because it uses the same icon and label as the original microg, it is indistinguishable from the original microg. Plesse change that.
#59 is about hiding the icon completely, which is a different request

**Comment by konradmoesch** [comment]
@oSumAtrIX could you please explain why you tagged #59? For me, it semms to be a completely different issue

**Comment by Ushie** [comment]
It's closed for the same reason

**Comment by konradmoesch** [comment]
in #59, no reason is given...

**Comment by oSumAtrIX** [comment]
No, it is https://github.com/ReVanced/GmsCore/issues/59#issuecomment-2045393724
