### ISSUE TITLE
feat (GmsCore): `Hide app icon from launcher`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/GmsCore#9]
### Feature description 

The current version of ReVanced GmsCore lacks an option within the app to hide the app icon from the app drawer/launcher. An option to do so would be very much appreciated if implemented. 

### Motivation 

GmsCore, once signed-in, is an app most people won't look back to and it's almost like a system app, which is very much needed for functionality but need not be present in the app drawer among other frequently used apps, as in opened every single time for any app usage. System apps are essential for background functionality but rarely interacted with directly. Hiding the GmsCore icon declutters the app drawer, keeping it focused on frequently used apps and providing a cleaner user experience.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please upstream this. The request is not a ReVanced specific one.

**Comment by ILoveOpenSourceApplications** [comment]
I still believe that `GmsCore` is what `VancedMicroG` was, but an update to the app, and one of the feature it had was this same one, though that was also a fork from [`microg/GmsCore`](https://github.com/microg/GmsCore). As I mentioned in my feature request, GmsCore for ReVanced is essential but mainly for background functionality and rarely plays any significance as an app in the drawer. And with the feature implementation, the user is given the choice to have it in their app drawer of they please to and not if they don't want to, which is a very important UI change and freedom of choice feature for every users perspective.

**Comment by oSumAtrIX** [comment]
The fork differs from Vanced MicroG and serves the same purpose as upstream for any app.

> GmsCore for ReVanced is essential but mainly for background functionality

That applies to upstream, and as I said, if that is the case, it would delegate eligibility to this fork.

**Comment by ILoveOpenSourceApplications** [comment]
> The fork differs from Vanced MicroG and serves the same purpose as upstream for any app.

It could be, given when ReVanced implements features for other apps to utilize it. But in it's current state, ReVanced GmsCore is only for those who wants to sign in to their YouTube account. Also, with this feature implementation users are given a toggle within the app to choose whether they want the app icon in their drawer or not, so not much changes apart from an extra toggle with the app option. 

I'm not arguing by any means, just stating why it's more significant for ReVanced GmsCore to have this feature rather than in upstream.

**Comment by oSumAtrIX** [comment]
> But in it's current state, ReVanced GmsCore is only for those who wants to sign in to their YouTube account

That is not true. In the current state the fork is as described before: for any app
Even if it wasn't it would still not justify implementing this feature here instead of upstream.

> Also, with this feature implementation users are given a toggle within the app to choose whether they want the app icon in their drawer or not, so not much changes apart from an extra toggle with the app option.

Once again, this is something you'd want to argue with upstream.

>  it's more significant for ReVanced GmsCore to have this feature rather than in upstream.

Your feature request does not contribute to either purpose this fork is made for. You have to discuss this with upstream.

**Comment by Sarun2515** [comment]
ทางแยกนี้ใช้การเปลี่ยนแปลงขั้นต่ำเพื่ออนุญาตให้ใช้ GmsCore ภายใต้ชื่อแพ็คเกจอื่นและเพื่อวัตถุประสงค์เช่นแอปที่ได้รับการแก้ไข คำขอคุณลักษณะของคุณไม่ได้มีส่วนช่วยในวัตถุประสงค์ใดวัตถุประสงค์หนึ่ง ซึ่งเป็นสาเหตุที่ตัวเลือกเดียวของคุณคือการอัปสตรีมนี้ เนื่องจากสิทธิ์ได้รับการมอบหมายจากอัปสตรีมไปยังที่เก็บข้อมูลนี้

**Comment by Sarun2515** [comment]
ฉันไม่คิดว่าฉันสามารถขอแบบเดียวกันกับอัปสตรีมได้เนื่องจาก GmsCore ดั้งเดิมนั้นถูกใช้โดยผู้ที่ไม่มีการสนับสนุนแอป Google ดั้งเดิมเช่นผู้ที่มีอุปกรณ์ Huawei หรือผู้ใช้ที่ไม่ต้องการให้ Google สอดแนมบนอุปกรณ์ของพวกเขา ซึ่งอาจ กำหนดให้พวกเขาเยี่ยมชมแอปบ่อยครั้งหากจำเป็น แต่สำหรับผู้ใช้ ReVanced มีเพียงการลงชื่อเข้าใช้บัญชี YouTube ของพวกเขาเท่านั้น และไม่มีอะไรเพิ่มเติม ดังนั้นจึงไม่ได้ให้ความสำคัญกับการมีแอปอยู่ในลิ้นชักแอป

**Comment by Sarun2515** [comment]
นั่นไม่เป็นความจริง ในสถานะปัจจุบัน ทางแยกนั้นเป็นไปตามที่อธิบายไว้ก่อนหน้านี้: สำหรับแอปใด ๆ
แม้ว่าจะไม่ใช่ แต่ก็คงไม่สามารถปรับใช้คุณลักษณะนี้ที่นี่แทนอัปสตรีมได้

นอกจากนี้ เมื่อใช้ฟีเจอร์นี้ ผู้ใช้จะได้รับการสลับภายในแอปเพื่อเลือกว่าพวกเขาต้องการไอคอนแอปในลิ้นชักหรือไม่ ดังนั้นจึงไม่มีการเปลี่ยนแปลงมากนักนอกเหนือจากการสลับเพิ่มเติมด้วยตัวเลือกแอป

นี่เป็นสิ่งที่คุณต้องการโต้แย้งกับต้นน้ำอีกครั้ง

มันสำคัญกว่าสำหรับ ReVanced GmsCore ที่จะมีฟีเจอร์นี้มากกว่าในอัปสตรีม

คำขอคุณลักษณะของคุณไม่ได้มีส่วนสนับสนุนวัตถุประสงค์ใด ๆ ที่ทางแยกนี้สร้างขึ้นมาเพื่อ คุณต้องหารือเรื่องนี้กับต้นน้ำ

**Comment by oSumAtrIX** [comment]
Please use English so everyone can read what you are writing.
