### ISSUE TITLE
Clarify the description in release

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/GmsCore#91]
Not all xiaomi or huawei phones should use the second version. For example, phones brought from regions other than China (therefore with the usual google play services) can use the first version. On the other hand, there are numerous brands other than xiaomi and huawei that dont have google play services, such as "oppo", "honor", etc.

It is not practical to list all brands like this. The more practical approach would be to use the common factor, such as "phones bought in China" or "phones without google play services"

Therefore, the description could be clarified to reflect this. 

Possible alternatives:

- No google play services (with a optional link on how to differentiate)
- Phones bought in China
- A short description on how to differentiate between phones with/without google play services and instruct users on the version to choose.

**Comment by oSumAtrIX** [comment]
> "phones bought in China"

I can buy a Google Pixel in China and a Xiaomi in the US.

> phones without google play services

GmsCore advertises this type of build for Huawai devices. GMS is not a dependant factor from what I am seeing for the reason of GmsCore being supposed to be used without any GMS to begin with.

Feel free to suggest anything else

**Comment by SodaWithoutSparkles** [comment]
> I can buy a Google Pixel in China and a Xiaomi in the US.

1. You cant really buy a pixel from official stores in China.
2. You can buy imported versions of pixels from china, but google is banned so they cant use gmscore anyway. The percentage of people who 1) use this fork of gmscore, 2) has phones bought in China, and 3) gone out of their way to bypass the government restrictions on google, is so low. This number is way lower than the number of people who get confused on "which version should I choose if I buy a xiaomi phone from country X (thats not China)".

------

Or alternatively, how about including a sentence like: "If your phone can use stock youtube, use the first version"? To my knowledge, since google is banned, no phones (officially) bought in china can watch stock youtube without reflashing the ROM to be the global version. This would also be catched by the check too.

Going back to your example, if one buys a pixel from US and ship it back to China, this check would catch this as well. Not that they could do anything tho, because again, google is banned and so does YouTube.

**Comment by oSumAtrIX** [comment]
I think this suggestion belongs upstream. GMS core advertises these builds for Huawai and that's what we also do

**Comment by SodaWithoutSparkles** [comment]
I dont see where (in upstream release) they target huawei specificly. 

Even if they do, I still dont see the reason for xiaomi being here as well. Xiaomi was having more users outside of china than huawei, and I see a lot of people getting confused.

If I see where they made the distinction (and the reasons for it), I would re-open the issue there instead. But I cant see where they even mention "huawei" on the release page there so I didnt open the issue to upstream.

To my knowledge, the reason for the build is for the certification of the device to google. If the manufacturer didnt certify the device for use with google play services (like huawei because of the sanctions), then gmscore cant run, regardless if you have gmscore. The second version was probably there to spoof the device or re-register it. 

But if the manufacturer certified the device, they can optionally install the google play service framework. _Most_ (but not all) xiaomi devices are sold in both China and Global market. So, _most_ xiaomi phones dont need the special treatment, especially for those sold in the global market.

But for the most cases, checking if they have stock youtube is okay enough.

**Comment by oSumAtrIX** [comment]
> they target huawei specificly

<img width="612" alt="image" src="https://github.com/ReVanced/GmsCore/assets/13122796/6acb7b5c-2719-4c99-93c0-00abb3c7780b">

>  I still dont see the reason for xiaomi being here as well.

Sure, I'll remove it then.

> To my knowledge, the reason for the build is for the certification of the device to google. If the manufacturer didnt certify the device for use with google play services (like huawei because of the sanctions), then gmscore cant run, regardless if you have gmscore. The second version was probably there to spoof the device or re-register it.
But if the manufacturer certified the device, they can optionally install the google play service framework. Most (but not all) xiaomi devices are sold in both China and Global market. So, most xiaomi phones dont need the special treatment, especially for those sold in the global market.

Please tell that upstream.
