### ISSUE TITLE
GMSCore not working on Huawei

### ISSUE THREAD

**Issue by Shaarigan** [ReVanced/GmsCore#92]
Hello,

I installed Revanced GSMCore on a hauwei MatePad Pro13.2 today along with a patched YouTube App and wasn't able to play any videos. YouTube kept buffering forever even when I followed these steps found here

https://www.reddit.com/r/revancedapp/comments/1bpm01z/a_guide_on_how_to_transition_to_revanced_gms_core

However, I also installed the official GMSCore to be able to use some Google Apps and tried to install unpatched YouTube. This worked ootb and was able to play videos without any issues. I guess there is something wrong with the GMSCore you offer?

**Comment by oSumAtrIX** [comment]
For support move to our links at https://revanced.app
