### ISSUE TITLE
Seems to break with custom domain gmail account..?

### ISSUE THREAD

**Issue by Kingminer7** [ReVanced/GmsCore#94]
So my email has a custom domain and it just won't load properly. My other email which uses @gmail.com is fine.
![Screenshot_20240613_102227_Gallery](https://github.com/ReVanced/GmsCore/assets/100500023/6d3fdc3a-cc58-4a0e-96a2-7f03092439b1)
My profile won't load properly for my normal email - it's hidden for privacy purposes

**Comment by oSumAtrIX** [comment]
Please report this issue to upstream.
