### ISSUE TITLE
GmSCore will not install on my device: Fire HD 8 2022

### ISSUE THREAD

**Issue by burstdragon323** [ReVanced/GmsCore#98]
GmSCore won't install on my Fire HD 8 2022, it keeps giving me an error
![image](https://github.com/ReVanced/GmsCore/assets/39740922/d8537e59-7b16-4153-9c63-d164474f3e6e)

Error Log: None, see Screenshot

**Comment by oSumAtrIX** [comment]
The APK supports ARM64-v8a. For support, move to one of our links at https://revanced.app.
